// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Tutor_Manager.Migrations
{
    [DbContext(typeof(Tutor_ManagerDatabaseContext))]
    partial class Tutor_ManagerDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tutor_Manager.Models.Administrator", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("Tutor_Manager.Models.Learner", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("GradeLevel")
                        .HasColumnType("int");

                    b.Property<string>("SchoolName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.ToTable("Learners");
                });

            modelBuilder.Entity("Tutor_Manager.Models.LearnerGuardian", b =>
                {
                    b.Property<int>("LearnerUserId")
                        .HasColumnType("int");

                    b.Property<int>("ParentUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimaryContact")
                        .HasColumnType("bit");

                    b.Property<string>("RelationshipToLearner")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LearnerUserId", "ParentUserId");

                    b.HasIndex("ParentUserId");

                    b.ToTable("LearnerGuardians");
                });

            modelBuilder.Entity("Tutor_Manager.Models.LearnerSubject", b =>
                {
                    b.Property<int>("LearnerUserId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("LearnerUserId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("LearnerSubjects");
                });

            modelBuilder.Entity("Tutor_Manager.Models.Parent", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("Tutor_Manager.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Tutor_Manager.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Tutor_Manager.Models.Tutor", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("DateApproved")
                        .HasColumnType("datetime2");

                    b.Property<string>("Qualification")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("VettingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Tutors");
                });

            modelBuilder.Entity("Tutor_Manager.Models.TutorSubject", b =>
                {
                    b.Property<int>("TutorUserId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<byte>("GradeLevel")
                        .HasColumnType("tinyint");

                    b.HasKey("TutorUserId", "SubjectId", "GradeLevel");

                    b.HasIndex("SubjectId");

                    b.ToTable("TutorSubjects");
                });

            modelBuilder.Entity("Tutor_Manager.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AltPhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Tutor_Manager.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Tutor_Manager.Models.Administrator", b =>
                {
                    b.HasOne("Tutor_Manager.Models.User", "User")
                        .WithOne("Administrator")
                        .HasForeignKey("Tutor_Manager.Models.Administrator", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tutor_Manager.Models.Learner", b =>
                {
                    b.HasOne("Tutor_Manager.Models.User", "User")
                        .WithOne("Learner")
                        .HasForeignKey("Tutor_Manager.Models.Learner", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tutor_Manager.Models.LearnerGuardian", b =>
                {
                    b.HasOne("Tutor_Manager.Models.Learner", "Learner")
                        .WithMany("Guardians")
                        .HasForeignKey("LearnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tutor_Manager.Models.Parent", "Parent")
                        .WithMany("Learners")
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Learner");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Tutor_Manager.Models.LearnerSubject", b =>
                {
                    b.HasOne("Tutor_Manager.Models.Learner", "Learner")
                        .WithMany("Subjects")
                        .HasForeignKey("LearnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tutor_Manager.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Learner");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Tutor_Manager.Models.Parent", b =>
                {
                    b.HasOne("Tutor_Manager.Models.User", "User")
                        .WithOne("Parent")
                        .HasForeignKey("Tutor_Manager.Models.Parent", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tutor_Manager.Models.Tutor", b =>
                {
                    b.HasOne("Tutor_Manager.Models.User", "User")
                        .WithOne("Tutor")
                        .HasForeignKey("Tutor_Manager.Models.Tutor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tutor_Manager.Models.TutorSubject", b =>
                {
                    b.HasOne("Tutor_Manager.Models.Subject", "Subject")
                        .WithMany("Tutors")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tutor_Manager.Models.Tutor", "Tutor")
                        .WithMany("SubjectsTaught")
                        .HasForeignKey("TutorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Tutor_Manager.Models.UserRole", b =>
                {
                    b.HasOne("Tutor_Manager.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tutor_Manager.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tutor_Manager.Models.Learner", b =>
                {
                    b.Navigation("Guardians");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Tutor_Manager.Models.Parent", b =>
                {
                    b.Navigation("Learners");
                });

            modelBuilder.Entity("Tutor_Manager.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Tutor_Manager.Models.Subject", b =>
                {
                    b.Navigation("Tutors");
                });

            modelBuilder.Entity("Tutor_Manager.Models.Tutor", b =>
                {
                    b.Navigation("SubjectsTaught");
                });

            modelBuilder.Entity("Tutor_Manager.Models.User", b =>
                {
                    b.Navigation("Administrator");

                    b.Navigation("Learner");

                    b.Navigation("Parent");

                    b.Navigation("Tutor");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
